services:

  http-component:
    build: 
      context: ./http-component
      dockerfile: ../component.Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - redis

  logic-component:
    build: 
      context: ./logic-component
      dockerfile: ../component.Dockerfile
    depends_on:
      - redis

  mqtt-component:
    build: 
      context: ./mqtt-component
      dockerfile: ../component.Dockerfile
    depends_on:
      - redis
      - broker-mqtt


#  serial-component:
#    build: 
#      context: ./serial-component
#      dockerfile: ../component.Dockerfile
#    devices:
#      - /dev/tty0:/dev/tty
#    depends_on:
#      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  broker-mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - type: bind
        source: ./broker-mqtt/mqtt.conf
        target: /mosquitto/config/mosquitto.conf
